# -*- coding: utf-8 -*-

from . import models
from . import res_partner_extend
from . import modelos
from . import pCloudModel
from . import pcloud_folder_file
from . import security_control
from . import contadores
from . import manuals
from . import copier_stock
from . import counter_web
from . import toner_web
from . import remote_printer
from . import cotizaciones_multiples
from . import cotizacion_hinerid
from . import stock_move_inherit
from . import copier_stock_extend
from . import copier_whatsapp_alerts
from . import copier_stock_whatsapp_extend
from . import printtracker_config
from . import copier_soporte
from . import whatsapp_config
from . import whatsapp_test_wizard
from . import whatsapp_template
from . import whatsapp_template_recipient
from . import whatsapp_notification
from . import whatsapp_mixin
from . import whatsapp_send_wizard
from . import whatsapp_template_test_wizard